name: GrpConst
version: "2.7.0"
license: "GPL-2.0-or-later"
date: 2026-08-14
description: |
    Constructing the Groups of a Given Order

authors:
    - name: Hans Ulrich Besche
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick

maintainers:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.11"

needed-pkgs:
    - name: "autpgrp"
      version: ">=1.6"
      url: "https://gap-packages.github.io/autpgrp/"
    - name: "irredsol"
      version: ">=1.2"
      url: "https://github.com/bh11/irredsol/"
    - name: "smallgrp"
      version: ">=1.4"
      url: "https://gap-packages.github.io/smallgrp/"

www: https://gap-packages.github.io/grpconst/
readme: README
packageinfo: https://gap-packages.github.io/grpconst/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/grpconst/releases/download/v2.7.0/grpconst-2.7.0.tar.gz

abstract: |
    The <span class="pkgname">GrpConst</span> package contains methods to construct up to isomorphism the groups of a given order. The FrattiniExtensionMethod constructs all soluble groups of a given order. On request it gives only those that are (or are not) nilpotent or supersoluble or that do (or do not) have normal Sylow subgroups for some given set of primes. The CyclicSplitExtensionMethod constructs all groups having a normal Sylow subgroup for orders of the type p^n * q. The method relies on the availability of a list of all groups of order p^n. The UpwardsExtensions algorithm takes as input a permutation group G and a positive integer s and returns a list of permutation groups, one for each extension of G by a soluble group of order a divisor of s. This method can be used to construct the non-soluble groups of a given order by taking the perfect groups of certain orders as input for G. The programs in this package have been used to construct a large part of the Small Groups library.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    constructing groups of small order, Frattini extension method, Cyclic split extension method, Upwards extension method.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BE26</span>]   <b class='BibAuthor'>Besche, H. U. and Eick, B.</b>,
     <i class='BibTitle'>GrpConst, Constructing the Groups of a Given Order,
             Version 2.7.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/grpconst/">https://gap-packages.github.io/grpconst/</a></span>.
    </p>
    

bibtex: |
    @misc{ GrpConst,
      author =           {Besche, H. U. and Eick, B.},
      title =            {{GrpConst},   {Constructing  the  Groups  of  a  Given
                          Order}, {V}ersion 2.7.0},
      month =            {Aug},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/grpconst/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{grpconst/}}},
      keywords =         {constructing groups of small order; Frattini extension
                          method;   Cyclic   split   extension  method;  Upwards
                          extension method},
      printedkey =       {BE26}
    }

