# GrpConst, chapter 6
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("grpconst04.tst");

# doc/upext.xml:42-57
gap> G := PerfectGroup( IsPermGroup, 120, 1 );
A5 2^1
gap> c := CyclicExtensions( G, 2 );;
gap> List( c, IdGroup );
[ [ 240, 94 ], [ 240, 93 ], [ 240, 89 ], [ 240, 90 ] ]
gap> H := c[1];
Group([ (3,4,7,5)(6,9,8,10)(11,15,13,16)(12,17,14,18)(19,21,20,22)
  (23,26,25,24), (3,6,4)(5,7,8)(9,11,12)(10,13,14)(15,18,19)(16,17,20)
  (21,23,24)(22,25,26), (1,2) ])
gap> CyclicExtensions( H, 2 );;
gap> List(last, IdGroup);
[ [ 480, 960 ], [ 480, 222 ], [ 480, 955 ], [ 480, 222 ], [ 480, 219 ], 
  [ 480, 950 ], [ 480, 219 ], [ 480, 949 ], [ 480, 957 ], [ 480, 957 ], 
  [ 480, 953 ], [ 480, 953 ] ]

# doc/upext.xml:58-66
gap> u := UpwardsExtensions( G, 4 );;
gap> List( u, Length );
[ 1, 4, 14 ]
gap> List( u[3], IdGroup);
[ [ 480, 960 ], [ 480, 959 ], [ 480, 222 ], [ 480, 219 ], [ 480, 950 ], 
  [ 480, 949 ], [ 480, 221 ], [ 480, 947 ], [ 480, 948 ], [ 480, 218 ], 
  [ 480, 955 ], [ 480, 957 ], [ 480, 953 ], [ 480, 946 ] ]

#
gap> STOP_TEST("grpconst04.tst", 1);
