# GrpConst, chapter 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("grpconst01.tst");

# doc/wrap.xml:28-42
gap> ConstructAllGroups( 60 );
[ <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, 
  <pc group of size 60 with 4 generators>, A5 ]

# doc/wrap.xml:43-48
gap> List( last, IdGroup );
[ [ 60, 4 ], [ 60, 13 ], [ 60, 6 ], [ 60, 2 ], [ 60, 1 ], [ 60, 7 ], 
  [ 60, 3 ], [ 60, 8 ], [ 60, 9 ], [ 60, 10 ], [ 60, 11 ], [ 60, 12 ], 
  [ 60, 5 ] ]

#
gap> STOP_TEST("grpconst01.tst", 1);
