# GrpConst, chapter 6
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("grpconst04.tst");

# doc/upext.xml:42-53
gap> G := PerfectGroup( IsPermGroup, 120, 1 );
A5 2^1
gap> c := CyclicExtensions( G, 2 );;
gap> SortedList( List( c, IdGroup ) );
[ [ 240, 89 ], [ 240, 90 ], [ 240, 93 ], [ 240, 94 ] ]
gap> H := First( c, x -> IdGroup( x ) = [ 240, 94 ] );;
gap> SortedList( List( CyclicExtensions( H, 2 ), IdGroup ) );
[ [ 480, 219 ], [ 480, 219 ], [ 480, 222 ], [ 480, 222 ], [ 480, 949 ], 
  [ 480, 950 ], [ 480, 953 ], [ 480, 953 ], [ 480, 955 ], [ 480, 957 ], 
  [ 480, 957 ], [ 480, 960 ] ]

# doc/upext.xml:54-62
gap> u := UpwardsExtensions( G, 4 );;
gap> List( u, Length );
[ 1, 4, 14 ]
gap> SortedList( List( u[3], IdGroup ) );
[ [ 480, 218 ], [ 480, 219 ], [ 480, 221 ], [ 480, 222 ], [ 480, 946 ], 
  [ 480, 947 ], [ 480, 948 ], [ 480, 949 ], [ 480, 950 ], [ 480, 953 ], 
  [ 480, 955 ], [ 480, 957 ], [ 480, 959 ], [ 480, 960 ] ]

#
gap> STOP_TEST("grpconst04.tst", 1);
