# GrpConst, chapter 5
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("grpconst03.tst");

# doc/cyclic.xml:37-44
gap> CyclicSplitExtensionMethod( 2,2,7, true );
rec( 
  both := [ <pc group of size 28 with 3 generators>, 
      <pc group of size 28 with 3 generators> ], 
  down := [ <pc group of size 28 with 3 generators>, 
      <pc group of size 28 with 3 generators> ], up := [  ] )

# doc/cyclic.xml:45-58
gap> CyclicSplitExtensionMethod( 2,2,[3,5], true );
rec( 
  both := [ <pc group of size 12 with 3 generators>, 
      <pc group of size 20 with 3 generators>, 
      <pc group of size 12 with 3 generators>, 
      <pc group of size 20 with 3 generators> ], 
  down := [ <pc group of size 12 with 3 generators>, 
      <pc group of size 20 with 3 generators>, 
      <pc group of size 20 with 3 generators>, 
      <pc group of size 12 with 3 generators>, 
      <pc group of size 20 with 3 generators> ], 
  up := [ <pc group of size 12 with 3 generators> ] )

# doc/cyclic.xml:83-87
gap> G := SmallGroup( 16, 10 );;
gap> CyclicSplitExtensionsUp( G, 3, true );
[ <pc group of size 48 with 5 generators> ]

# doc/cyclic.xml:88-94
gap> G := SylowSubgroup( SymmetricGroup(4), 2);
Group([ (1,2), (3,4), (1,3)(2,4) ])
gap> CyclicSplitExtensionsDown( G, 3 );
[ rec( code := 119814529, order := 24 ), 
  rec( code := 2837724033, order := 24 ) ]

#
gap> STOP_TEST("grpconst03.tst", 1);
