# GrpConst, chapter 4
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("grpconst02.tst");

# doc/frattext.xml:72-86
gap> flags := rec( nonnilpot := true, pnormal := [3] );
rec( nonnilpot := true, pnormal := [ 3 ] )
gap> grps := FrattiniExtensionMethod( 24, flags, true );
[ <pc group of size 24 with 4 generators>, 
  <pc group of size 24 with 4 generators>, 
  <pc group of size 24 with 4 generators>, 
  <pc group of size 24 with 4 generators>, 
  <pc group of size 24 with 4 generators>, 
  <pc group of size 24 with 4 generators>, 
  <pc group of size 24 with 4 generators> ]
gap> List( last, IdGroup );
[ [ 24, 1 ], [ 24, 5 ], [ 24, 8 ], [ 24, 6 ], [ 24, 7 ], [ 24, 4 ], 
  [ 24, 14 ] ]

# doc/frattext.xml:87-104
gap> FrattiniExtensionMethod( 8 );
[ rec( code := 323, extdim := [ 2, 2 ], first := [ 1, 1, 2 ], 
      isFrattiniFree := false, isUnique := true, order := 8, 
      socledim := [ 1 ] ), 
  rec( code := 34, extdim := [ 2 ], first := [ 1, 1, 3 ], 
      isFrattiniFree := false, isUnique := true, order := 8, 
      socledim := [ 1, 1 ] ), 
  rec( code := 36, extdim := [ 2 ], first := [ 1, 1, 3 ], 
      isFrattiniFree := false, isUnique := true, order := 8, 
      socledim := [ 1, 1 ] ), 
  rec( code := 2343, extdim := [ 2 ], first := [ 1, 1, 3 ], 
      isFrattiniFree := false, isUnique := true, order := 8, 
      socledim := [ 1, 1 ] ), 
  rec( code := 0, extdim := [  ], first := [ 1, 1, 4 ], 
      isFrattiniFree := true, isUnique := true, order := 8, 
      socledim := [ 1, 1, 1 ] ) ]

# doc/frattext.xml:137-146
gap> flags := rec( nonsupsol := true );
rec( nonsupsol := true )
gap> FrattiniFactorCandidates( 24, flags, true );
[ <pc group of size 24 with 4 generators>, 
  <pc group of size 12 with 3 generators>, 
  <pc group of size 24 with 4 generators> ]
gap> List(last, IdGroup);
[ [ 24, 12 ], [ 12, 3 ], [ 24, 13 ] ]

# doc/frattext.xml:170-181
gap> G := SmallGroup( 24, 12 );
<pc group of size 24 with 4 generators>
gap> FrattiniSubgroup(G);
Group([  ])
gap> FrattiniExtensions( G, 48, true );
[ <pc group of size 48 with 5 generators>, 
  <pc group of size 48 with 5 generators>, 
  <pc group of size 48 with 5 generators> ]
gap> List( last, IdGroup);
[ [ 48, 29 ], [ 48, 30 ], [ 48, 28 ] ]

# doc/frattext.xml:182-197
gap> cand := FrattiniFactorCandidates( 6, rec() );
[ rec( code := 25, extdim := [  ], first := [ 1, 2, 3 ], 
      isFrattiniFree := true, isUnique := true, order := 6, socledim := [ 1 ] 
     ), 
  rec( code := 1, extdim := [  ], first := [ 1, 1, 3 ], 
      isFrattiniFree := true, isUnique := true, order := 6, 
      socledim := [ 1, 1 ] ) ]
gap> FrattiniExtensions( cand, 12 );
[ rec( code := 6442, extdim := [ 2 ], first := [ 1, 2, 3 ], 
      isFrattiniFree := false, isUnique := true, order := 12, 
      socledim := [ 1 ] ), 
  rec( code := 266, extdim := [ 2 ], first := [ 1, 1, 3 ], 
      isFrattiniFree := false, isUnique := true, order := 12, 
      socledim := [ 1, 1 ] ) ]

#
gap> STOP_TEST("grpconst02.tst", 1);
